CREATE DATABASE /*!32312 IF NOT EXISTS*/`task4` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `task4`;

/*Table structure for table `employees` */

DROP TABLE IF EXISTS `colours`;

CREATE TABLE `colours` (
  `Color` VARCHAR(20) NOT NULL,
  `Category` VARCHAR(20) DEFAULT NULL,
  `Hex` VARCHAR(10) DEFAULT NULL,
  `Rgba` VARCHAR(30) DEFAULT NULL,
  `Type` VARCHAR(25) DEFAULT NULL,
  `URL` VARCHAR(25) DEFAULT NULL,
  `Width` INT(11) DEFAULT NULL,
  `Height` INT(11) DEFAULT NULL,
  PRIMARY KEY (`Color`),
  KEY `Hex` (`Hex`)
) ENGINE=MYISAM AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `dessert`;

CREATE TABLE `dessert` (
  `DessertID` VARCHAR(11) NOT NULL,
  `Type` VARCHAR(25) DEFAULT NULL,
  `Name` VARCHAR(25) DEFAULT NULL,
  `ImageURl` VARCHAR(10) DEFAULT NULL,
  `ImageWidth` VARCHAR(30) DEFAULT NULL,
  `ImageHeight` VARCHAR(20) DEFAULT NULL,
  `ThumbnailURL` VARCHAR(25) DEFAULT NULL,
  `ThumbnailWidth` VARCHAR(25) DEFAULT NULL,
  `ThumbnailHeight` VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (`DessertID`),
  KEY `Name` (`Name`)
) ENGINE=MYISAM AUTO_INCREMENT=29 DEFAULT CHARSET=utf8;